check for nothing in plaintext
bitprj/Intro-To-Serverless pull request #342
Opened 2021-07-09 18:35 UTC by ganning127

## Changes made
* Added code to make sure week 1 morse code checks for an empty `plaintext`, or if `plaintext` was not entered at all.

Closes #252

2021-07-09 18:53 UTC, emsesc approved these changes

2021-07-10 07:38 UTC, blueboxes requested changes

2021-07-10 07:38 UTC, blueboxes commented on .bit/responses/1.8-Week 1 Step 8.md
> +6. Now that we checked if the user has entered nothing, we can add code that will execute when the user has entered something for `plaintext`. Add this after the `if`.
I am not sure this is perfectly clear as it is not directly after the if. The next line also does not have the extra bracket needed to make it work. Not sure how to make it clearer without the entire code sample.

2021-07-10 19:46 UTC, blueboxes approved these changes

2021-07-10 20:20 UTC, merged