Update 4.2-Week 4 Step 2.md
bitprj/Intro-To-Serverless pull request #374
Opened 2021-07-18 15:54 UTC by dtetreau251

## Changes made
* Deleted onsubmit in html
* Deleted verbiage referencing getImage function

Closes #[issue number]

2021-07-18 17:50 UTC, blueboxes approved these changes

2021-07-18 18:35 UTC, blueboxes requested changes
The sample solution would also need to be updated. Like the other post is adding event handler JS needs to be added at the end of the file to ensure DOM has loaded.

2021-07-18 20:57 UTC, dtetreau251 commented
> The sample solution would also need to be updated. Like the other post is adding event handler JS needs to be added at the end of the file to ensure DOM has loaded.

The event listener/anonymous function is in a separate file from the html. It is triggered by a form submission. I indicated that the script tag linking the html file to the js file needed to be at the end of the body. This is how I've always seen it done to ensure the page has loaded. Could you clarify? Also, I have created a separate issue to address all the solution files in week 4.

2021-07-19 06:36 UTC, blueboxes commented
> In the md file, I indicated that the script tag linking the html file to the js file needed to be at the end of the body. This is how I've always seen it done to ensure the page has loaded. Could you clarify?

It is common to put JS files in the head or script blocks. This does not work as the page may not have loaded (I said DOM, which is the Document Object Model aka map of the items on the page that Js uses). Adding it at the end works perfectly well. There are other ways instead like the defer attribute or using an on loaded event handler to add the other event handlers. Though no need to mention that.

I could not see the note to add the JS to the end though could have been in the previous step.

2021-07-19 06:36 UTC, blueboxes approved these changes

2021-07-19 13:09 UTC, merged