Week 4 sample solutions
bitprj/Intro-To-Serverless pull request #382
Opened 2021-07-19 13:44 UTC by ganning127

## Changes made
* Updated the sample solutions for the steps with updated event listeneres and such. 

Closes #377

2021-07-19 17:54 UTC, emsesc requested changes
I think you missed one here, and if you're changing event listeners as well, you can update the rest of Week 4 solutions as well. (It's just for jQuery that steps 5, 6, 7 don't include, but 5, 6, 7 don't include event listeners yet)

2021-07-19 17:54 UTC, emsesc commented on .bit/tests/sample-solutions/week4/4.4/index.html
> +                  <form id="bunnForm" onsubmit="getImage(event)" enctype="multipart/form-data">
I think you missed this one

2021-07-20 13:42 UTC, ganning127 commented on .bit/tests/sample-solutions/week4/4.4/index.html
> +                  <form id="bunnForm" onsubmit="getImage(event)" enctype="multipart/form-data">
whoopsies

2021-07-20 14:10 UTC, emsesc approved these changes
thanks 🐱

2021-07-20 18:22 UTC, blueboxes approved these changes

2021-07-20 23:47 UTC, merged