#439 Updated branch definition
bitprj/Intro-To-Serverless pull request #507
Opened 2022-07-03 10:56 UTC by blueboxes

## Changes made
* Text update to definitions

Closes #439

2022-07-12 18:58 UTC, emsesc requested changes

2022-07-20 02:48 UTC, ganning127 requested changes

2022-07-20 02:48 UTC, ganning127 commented on .bit/responses/1.1-Week 1 Step 1.md
> +Creating a new **branch** on a repository is like create another line of development that is isolated from other code. You would do this when you **want to make changes to your code without effecting
is like "creating another line..."

2022-07-20 18:29 UTC, lechnerc77 requested changes

2022-07-20 18:29 UTC, lechnerc77 commented on .bit/responses/1.1-Week 1 Step 1.md
> +Creating a new **branch** on a repository is like create another line of development that is isolated from other code. You would do this when you **want to make changes to your code without effecting
I am struggeling a bit with the word "isolated" as a branch is not isolated, but still attached to the main branch. Perhaps ".. is like creating a new version or another line of development of your repository"

2022-07-20 18:29 UTC, lechnerc77 commented on .bit/responses/1.1-Week 1 Step 1.md
> +Once you make changes on **a forked repository or another branch,** you might need to bring the changes into the `main` repository. This allows YOUR changes to be visible in the main project! *You ar
Proposal for wording: 
"Once you make changes on **a fork or a branch**, you might want to bring the changes into the *main* branch of the branched/forked repository. ..."

2022-07-31 14:02 UTC, blueboxes commented
@lechnerc77  @ganning127  thanks for your feedback, I have updated based on the comments (sorry for the delay)

2022-08-01 08:24 UTC, lechnerc77 approved these changes
Looks good!

2022-09-10 07:33 UTC, closed without merging