Selecting Random Data Warning
bitprj/Intro-To-Serverless pull request #517
Opened 2022-07-21 02:07 UTC by emsesc

## Changes made
* Explained best practices for querying data
* Added resources for real-world applications

Closes #458

2022-07-21 14:59 UTC, lechnerc77 requested changes
One small remark to keep the note consistent with the setup of the sample i.e. the SQL API of Cosmos DB

2022-07-21 14:59 UTC, lechnerc77 commented on .bit/responses/3.8-Week 3 Step 8.md
> +> ⚠️ **Warning:** Keep in mind that *querying for ALL data* at the same time ***is not good practice.*** Data should only be queried on-demand when the user requires it. In this case, the user only n
For the built In functionality I would distinguish the different APIs. The "built-in functionalities" currently points to the Mongo DB API, which is not used in the curriculum. I would therefore put in SQL API too 

Proposal: 
In this case, the user only needs *one random secret*, so in a "real-world application," we would utilize built-in functionalities for [MongoAPI](https://www.mongodb.com/docs/manual/reference/operator/aggregation/sample/) or [stored procedures](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/how-to-write-stored-procedures-triggers-udfs?tabs=javascript#stored-procedures). The situation is a bit more tricky for SQL API, you find more information in this [blog post](http://www.titov.net/2005/09/21/do-not-use-order-by-rand-or-how-to-get-random-rows-from-table/)

2022-07-23 08:38 UTC, lechnerc77 approved these changes

2022-07-24 17:29 UTC, ganning127 approved these changes

2022-07-24 17:29 UTC, merged