Week 3 Step 1 Revisions
bitprj/Intro-To-Serverless pull request #518
Opened 2022-07-22 03:06 UTC by emsesc

## Changes made
* LRS config
* Explain dangers of public endpoint
* Add note about storage explorer

Closes #451

2022-07-22 06:27 UTC, lechnerc77 requested changes
One super small remark :-)

2022-07-22 06:27 UTC, lechnerc77 commented on .bit/responses/3.1-Week 3 Step 1.md
> +> ⚠️ **Warning:** The set-up for your blob storage container makes the endpoint **publicly accessible.** This means that it is *not* safe for real-world applications since it allows the potential for
To be consistent we should use Blob with capital "B" if we are addressing the Azure Service in the document

2022-07-23 08:37 UTC, lechnerc77 approved these changes

2022-07-24 17:33 UTC, ganning127 approved these changes

2022-07-24 17:33 UTC, merged