Week 3 Step 2 Revisions
bitprj/Intro-To-Serverless pull request #519
Opened 2022-07-22 14:20 UTC by emsesc

## Changes made
* Added comparison of bindings and SDKs
* Consistent screenshot themes
* Added reminder on local.settings.json
* Added tip in testing to see what happens when two files of the same name are uploaded

Closes #452

2022-07-23 08:36 UTC, lechnerc77 requested changes
One minor editorial point

2022-07-23 08:36 UTC, lechnerc77 commented on .bit/responses/3.2-Week 3 Step 2.md
> +> ❗️ **Note:** In this project, we will be using the approach of **SDKs** and **API calls** to connect our Blob Storage and Azure Function. Another way to do this is through [binding](https://docs.mi
Instead of faster (which might be misunderstood with regards to performance or throughput I would state easier or more convenient

2022-07-23 16:19 UTC, lechnerc77 approved these changes

2022-07-24 17:37 UTC, ganning127 approved these changes

2022-07-24 17:37 UTC, merged